In [1]:
# import libraries
import os
import pandas as pd

In [2]:
# variable for download date of file
download_date = "Aug_24"

In [3]:
# load csv file
rankings_file = "../rankings/"+ download_date + ".csv"
rankings = pd.read_csv(rankings_file)

In [4]:
rankings

,RK,TIERS,PLAYER NAME,TEAM,POS,BYE WEEK,SOS SEASON,ECR VS. ADP
0,1,1,Christian McCaffrey,CAR,RB1,13,2 out of 5 stars,0
1,2,1,Dalvin Cook,MIN,RB2,7,3 out of 5 stars,0
2,3,1,Alvin Kamara,NO,RB3,6,2 out of 5 stars,+1
3,4,1,Derrick Henry,TEN,RB4,13,3 out of 5 stars,-1
4,5,1,Ezekiel Elliott,DAL,RB5,7,2 out of 5 stars,0
...,...,...,...,...,...,...,...,...
786,787,16,Austin Mack,NYG,WR322,10,3 out of 5 stars,-
787,788,16,Keith Kirkwood,CAR,WR323,13,5 out of 5 stars,-
788,789,16,Matthew Slater,NE,WR324,14,4 out of 5 stars,-
789,790,16,Kyle Allen,WAS,QB68,9,4 out of 5 stars,-
790,791,16,Alex Bachman,NYG,WR325,10,3 out of 5 stars,-

In [5]:
# create position column from POS column
rankings["Position"] = rankings["POS"].astype(str).str[0:2]
rankings

,RK,TIERS,PLAYER NAME,TEAM,POS,BYE WEEK,SOS SEASON,ECR VS. ADP,Position
0,1,1,Christian McCaffrey,CAR,RB1,13,2 out of 5 stars,0,RB
1,2,1,Dalvin Cook,MIN,RB2,7,3 out of 5 stars,0,RB
2,3,1,Alvin Kamara,NO,RB3,6,2 out of 5 stars,+1,RB
3,4,1,Derrick Henry,TEN,RB4,13,3 out of 5 stars,-1,RB
4,5,1,Ezekiel Elliott,DAL,RB5,7,2 out of 5 stars,0,RB
...,...,...,...,...,...,...,...,...,...
786,787,16,Austin Mack,NYG,WR322,10,3 out of 5 stars,-,WR
787,788,16,Keith Kirkwood,CAR,WR323,13,5 out of 5 stars,-,WR
788,789,16,Matthew Slater,NE,WR324,14,4 out of 5 stars,-,WR
789,790,16,Kyle Allen,WAS,QB68,9,4 out of 5 stars,-,QB
790,791,16,Alex Bachman,NYG,WR325,10,3 out of 5 stars,-,WR

In [6]:
# numeric value for Strength of Schedule
rankings["SOS SEASON"] = rankings["SOS SEASON"].astype(str).str[0:1]
rankings.to_csv("../analysis/full.csv")
rankings

,RK,TIERS,PLAYER NAME,TEAM,POS,BYE WEEK,SOS SEASON,ECR VS. ADP,Position
0,1,1,Christian McCaffrey,CAR,RB1,13,2,0,RB
1,2,1,Dalvin Cook,MIN,RB2,7,3,0,RB
2,3,1,Alvin Kamara,NO,RB3,6,2,+1,RB
3,4,1,Derrick Henry,TEN,RB4,13,3,-1,RB
4,5,1,Ezekiel Elliott,DAL,RB5,7,2,0,RB
...,...,...,...,...,...,...,...,...,...
786,787,16,Austin Mack,NYG,WR322,10,3,-,WR
787,788,16,Keith Kirkwood,CAR,WR323,13,5,-,WR
788,789,16,Matthew Slater,NE,WR324,14,4,-,WR
789,790,16,Kyle Allen,WAS,QB68,9,4,-,QB
790,791,16,Alex Bachman,NYG,WR325,10,3,-,WR

In [7]:
# reorder columns in dataframe 
preference = rankings[["PLAYER NAME","TEAM","RK","TIERS","SOS SEASON","BYE WEEK"]]
#preference.to_csv("../analysis/full.csv")
preference

             PLAYER NAME TEAM   RK  TIERS SOS SEASON BYE WEEK
0    Christian McCaffrey  CAR    1      1          2       13
1            Dalvin Cook  MIN    2      1          3        7
2           Alvin Kamara   NO    3      1          2        6
3          Derrick Henry  TEN    4      1          3       13
4        Ezekiel Elliott  DAL    5      1          2        7
..                   ...  ...  ...    ...        ...      ...
786          Austin Mack  NYG  787     16          3       10
787       Keith Kirkwood  CAR  788     16          5       13
788       Matthew Slater   NE  789     16          4       14
789           Kyle Allen  WAS  790     16          4        9
790         Alex Bachman  NYG  791     16          3       10

[791 rows x 6 columns]

In [8]:
# set Running Back dataframe
running_backs = preference.loc[rankings['Position'] == "RB"]
running_backs = running_backs[running_backs["TIERS"]<11]
running_backs = running_backs.reset_index(drop=True)
running_backs.to_csv("../analysis/running_backs.csv")

In [9]:
# set Wide Receiver dataframe
wide_receiver = preference.loc[rankings['Position'] == "WR"]
wide_receiver = wide_receiver[wide_receiver["TIERS"]<11]
wide_receiver = wide_receiver.reset_index(drop=True)
wide_receiver.to_csv("../analysis/wide_receiver.csv")

In [10]:
# set Quarterback dataframe
quarterback = preference.loc[rankings['Position'] == "QB"]
quarterback = quarterback[quarterback["TIERS"]<9]
quarterback = quarterback.reset_index(drop=True)
quarterback.to_csv("../analysis/quarterback.csv")

In [11]:
# set Tight End dataframe
tight_end = preference.loc[rankings['Position'] == "TE"]
tight_end = tight_end[tight_end["TIERS"]<13]
tight_end = tight_end.reset_index(drop=True)
tight_end.to_csv("../analysis/tight_end.csv")

In [12]:
# set Defense/Special Teams dataframe
dst = preference.loc[rankings['Position'] == "DS"]
#dst = dst[dst["TIERS"]<6]
dst = dst.reset_index(drop=True)
dst.to_csv("../analysis/dst.csv")

In [13]:
# set Kicker dataframe
kicker = preference.loc[rankings['Position'] == "KS"]
kicker = kicker[kicker["TIERS"]<4]
kicker = kicker.reset_index(drop=True)
kicker
#kicker.to_csv("../analysis/kicker.csv")

Empty DataFrame
Columns: [PLAYER NAME, TEAM, RK, TIERS, SOS SEASON, BYE WEEK]
Index: []