In [1]:
# import libraries
import os
import pandas as pd

In [2]:
# variable for download date of file
download_date = "Aug_15"

In [3]:
# load csv file
rankings_file = "../rankings/"+ download_date + ".csv"
rankings = pd.read_csv(rankings_file)

In [4]:
rankings

,RK,TIERS,PLAYER NAME,TEAM,POS,BYE WEEK,SOS SEASON,ECR VS. ADP
0,1,1,Christian McCaffrey,CAR,RB1,13,2 out of 5 stars,0
1,2,1,Dalvin Cook,MIN,RB2,7,3 out of 5 stars,0
2,3,1,Derrick Henry,TEN,RB3,13,3 out of 5 stars,0
3,4,1,Alvin Kamara,NO,RB4,6,2 out of 5 stars,0
4,5,1,Ezekiel Elliott,DAL,RB5,7,2 out of 5 stars,0
...,...,...,...,...,...,...,...,...
534,535,14,Phillip Walker,CAR,QB49,13,4 out of 5 stars,-
535,536,14,Nick Foles,CHI,QB50,10,2 out of 5 stars,-
536,537,14,Brandon Bolden,NE,RB150,14,3 out of 5 stars,-
537,538,14,Jarrett Stidham,NE,QB51,14,5 out of 5 stars,-
538,539,14,Dontrell Hilliard,HOU,RB151,10,4 out of 5 stars,-

In [5]:
# create position column from POS column
rankings["Position"] = rankings["POS"].astype(str).str[0:2]
rankings

,RK,TIERS,PLAYER NAME,TEAM,POS,BYE WEEK,SOS SEASON,ECR VS. ADP,Position
0,1,1,Christian McCaffrey,CAR,RB1,13,2 out of 5 stars,0,RB
1,2,1,Dalvin Cook,MIN,RB2,7,3 out of 5 stars,0,RB
2,3,1,Derrick Henry,TEN,RB3,13,3 out of 5 stars,0,RB
3,4,1,Alvin Kamara,NO,RB4,6,2 out of 5 stars,0,RB
4,5,1,Ezekiel Elliott,DAL,RB5,7,2 out of 5 stars,0,RB
...,...,...,...,...,...,...,...,...,...
534,535,14,Phillip Walker,CAR,QB49,13,4 out of 5 stars,-,QB
535,536,14,Nick Foles,CHI,QB50,10,2 out of 5 stars,-,QB
536,537,14,Brandon Bolden,NE,RB150,14,3 out of 5 stars,-,RB
537,538,14,Jarrett Stidham,NE,QB51,14,5 out of 5 stars,-,QB
538,539,14,Dontrell Hilliard,HOU,RB151,10,4 out of 5 stars,-,RB

In [11]:
# numeric value for Strength of Schedule
rankings["SOS SEASON"] = rankings["SOS SEASON"].astype(str).str[0:1]
rankings[rankings["TIERS"]>0]
rankings

,RK,TIERS,PLAYER NAME,TEAM,POS,BYE WEEK,SOS SEASON,ECR VS. ADP,Position
0,1,1,Christian McCaffrey,CAR,RB1,13,2,0,RB
1,2,1,Dalvin Cook,MIN,RB2,7,3,0,RB
2,3,1,Derrick Henry,TEN,RB3,13,3,0,RB
3,4,1,Alvin Kamara,NO,RB4,6,2,0,RB
4,5,1,Ezekiel Elliott,DAL,RB5,7,2,0,RB
...,...,...,...,...,...,...,...,...,...
534,535,14,Phillip Walker,CAR,QB49,13,4,-,QB
535,536,14,Nick Foles,CHI,QB50,10,2,-,QB
536,537,14,Brandon Bolden,NE,RB150,14,3,-,RB
537,538,14,Jarrett Stidham,NE,QB51,14,5,-,QB
538,539,14,Dontrell Hilliard,HOU,RB151,10,4,-,RB

In [8]:
# reorder columns in thdataframe 
preference = rankings[["PLAYER NAME","TEAM","RK","TIERS","SOS SEASON","BYE WEEK"]]
preference

             PLAYER NAME TEAM   RK  TIERS SOS SEASON BYE WEEK
0    Christian McCaffrey  CAR    1      1          2       13
1            Dalvin Cook  MIN    2      1          3        7
2          Derrick Henry  TEN    3      1          3       13
3           Alvin Kamara   NO    4      1          2        6
4        Ezekiel Elliott  DAL    5      1          2        7
..                   ...  ...  ...    ...        ...      ...
534       Phillip Walker  CAR  535     14          4       13
535           Nick Foles  CHI  536     14          2       10
536       Brandon Bolden   NE  537     14          3       14
537      Jarrett Stidham   NE  538     14          5       14
538    Dontrell Hilliard  HOU  539     14          4       10

[539 rows x 6 columns]

In [9]:
running_backs = preference.loc[rankings['Position'] == "RB"]
running_backs

             PLAYER NAME TEAM   RK  TIERS SOS SEASON BYE WEEK
0    Christian McCaffrey  CAR    1      1          2       13
1            Dalvin Cook  MIN    2      1          3        7
2          Derrick Henry  TEN    3      1          3       13
3           Alvin Kamara   NO    4      1          2        6
4        Ezekiel Elliott  DAL    5      1          2        7
..                   ...  ...  ...    ...        ...      ...
527        Dedrick Mills  DET  528     14          0        9
528           Derek Watt  PIT  529     14          5        7
532         Lamar Miller  WAS  533     14          3        9
536       Brandon Bolden   NE  537     14          3       14
538    Dontrell Hilliard  HOU  539     14          4       10

[151 rows x 6 columns]